'use client'

import { Inter } from "next/font/google";
import "../globals.css"
// import Header from "@/components/landing-page/Header";
import { usePathname } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;

}>) {

const pathname=usePathname()

  return (
    <html lang="en">
     
      <body className={inter.className}>
      {/* {pathname ==='/admin' &&<Header/>} */}
        {children}
        </body>
    </html>
  );
}
